### ISSUE TITLE
The SETUP process miss the language configuration 

### ISSUE THREAD

**Issue by hacktivateit** [LAB1100/1100CC#3]
After installing 1100CC with the setup process described in this repo i found that the CMS interface (and also the 404 error page) was missing all the translated labels, showing only the string identifiers

Example:
![image](https://user-images.githubusercontent.com/761740/202314104-ca7cc1e4-a156-4bdd-9d91-9ac214b664af.png)

I fixed by adding a default language in the cms_language table
```sql 
INSERT INTO `cms_language` (`lang_code`, `label`, `user`, `is_default`) VALUES ('en', 'English', '1', '1');
```

This is missing in the setup process and in the sql files that need to be imported

**Comment by LAB1100** [comment]
Thanks, we've now included a default language in the setup procedure.
